remove logs and small tweaks

diff --git a/src/charms/pdoro_cb b/src/charms/pdoro_cb
--- a/src/charms/pdoro_cb
+++ b/src/charms/pdoro_cb
@@ -8,43 +8,32 @@ zparseopts -D -E -F -- \
   || return 1
 
 local phase=${phaseArg[2]}
+local message=$*
 
 if [[ -z "$phase" ]]
-  then echo "phase is required"; exit 1
+  then printf "phase is required"; exit 1
 fi
 
 if [[ "$phase" != "started" && "$phase" != "ended" ]]
-  then echo "phase must be 'started' or 'ended'"; exit 1
+  then printf "phase must be 'started' or 'ended'"; exit 1
 fi
-
-echo "${phase} 1"
 
 TIME=`date +%H:%M:%S`
 YEAR=`date +%Y`
 MONTH=`date +%b`
 THIS_MONTH_FOLDER=pomodoro/${YEAR}/${MONTH}
 
-echo "${phase} 2"
-
 function appendPomodoroInfoToLog() {
-  echo "${*} ${phase} at ${TIME}"
-  log_to_zsb "${*} ${phase} at ${TIME}" $THIS_MONTH_FOLDER
+  # second message decoration
+  log_to_zsb "${message} ${phase} at ${TIME}" $THIS_MONTH_FOLDER
 }
 
 
-echo "${phase} 3"
-
 if [[ "$phase" = "started" ]]; then
-  echo "you started"
   log_to_zsb " " $THIS_MONTH_FOLDER
 fi
 
-
-echo "${phase} 4"
-
 appendPomodoroInfoToLog
-
-echo "${phase} 5"
 
 if [[ "$phase" = "ended" ]]; then
   alert $@ &
